/* user actions */
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const ERROR_USER_LOGIN = 'ERROR_USER_LOGIN';
export const ERROR_USER_SIGNUP = 'ERROR_USER_SIGNUP';
export const SUCCESS_USER_SIGNUP = 'SUCCESS_USER_SIGNUP';
export const RECEIVED_USER_PROFILE = 'RECEIVED_USER_PROFILE';
export const ERROR_USER_FORGOT = 'ERROR_USER_FORGOT';
export const SUCCESS_USER_FORGOT = 'SUCCESS_USER_FORGOT';
export const RECEIVED_USER_FORGOT = 'RECEIVED_USER_FORGOT';
export const ERROR_USER_RESETPW = 'ERROR_USER_RESETPW';
export const SUCCESS_USER_RESETPW = 'SUCCESS_USER_RESETPW';
export const FETCHING_USER_RESETPW = 'FETCHING_USER_RESETPW';
